SELECT MIN(TOTALPRICE),MAX(TOTALPRICE), COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE)
FROM SALES WHERE CITY='ÝSTANBUL'

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE), COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE)
FROM SALES WHERE CITY='ANKARA'

SELECT CITY,
MIN(TOTALPRICE) AS MINRPRÝCE,
MAX(TOTALPRICE) AS MAXPRÝCE,
COUNT(FICHENO) AS ROWCOUNT_ ,
SUM(TOTALPRICE) TOTALPRÝCE,
AVG(TOTALPRICE) AVGPRÝCE
FROM SALES GROUP BY CITY

SELECT CITY,
SUM(TOTALPRICE) 
FROM SALES 
GROUP BY CITY 
order by sum(TOTALPRICE) desc


SELECT top 10 CITY,
SUM(TOTALPRICE) 
FROM SALES 
GROUP BY CITY 
order by sum(TOTALPRICE) desc



UPDATE SALES SET DATE2 = CONVERT(DATE,DATE_)

SELECT * FROM SALES WHERE CITY ='ANKARA'
AND DATE2 = '2019-02-02'
ORDER BY DATE_


SELECT CITY, DATE2, SUM(TOTALPRICE) AS TOTALPRICE

FROM SALES WHERE CITY='ANKARA'
GROUP BY CITY, DATE2
ORDER BY CITY,DATE2



SELECT DATE2, CITY, SUM(TOTALPRICE) FROM SALES
WHERE DATE2='2019-01-01'
GROUP BY DATE2 , CITY
ORDER BY DATE2, CITY




--MAÐAZALARIN AYLARA GÖRE SATIÞ RAKAMALRI






SELECT date2, datepart(month,date2) as month FROM SALES group by date2 order by date2 asc

UPDATE SALES SET monthname ='01. OCAK' WHERE DATEPART(MONTH, DATE2)=1
UPDATE SALES SET monthname ='02. ÞUBAT' WHERE DATEPART(MONTH, DATE2)=2
UPDATE SALES SET monthname ='03.MART' WHERE DATEPART (MONTH, DATE2)=3
UPDATE SALES SET monthname ='04.NISAN' WHERE DATEPART(MONTH, DATE2)=4
UPDATE SALES SET monthname ='05.MAYIS' WHERE DATEPART (MONTH, DATE2)=5
UPDATE SALES SET monthname ='06.HAZIRAN' WHERE DATEPART(MONTH, DATE2)=6
UPDATE SALES SET monthname ='07.TEMMUZ' WHERE DATEPART(MONTH, DATE2)=7
UPDATE SALES SET monthname ='08.AÐUSTOS' WHERE DATEPART(MONTH, DATE2)=8
UPDATE SALES SET monthname ='09.eylül' WHERE DATEPART(MONTH, DATE2)=9
UPDATE SALES SET monthname ='10.ekim' WHERE DATEPART(MONTH, DATE2)=10
UPDATE SALES SET monthname ='11.kasým' WHERE DATEPART(MONTH, DATE2)=11
UPDATE SALES SET monthname ='12.aralýk' WHERE DATEPART(MONTH, DATE2)=12


select CITY, monthname, sum(TOTALPRICE) as totalprice from sales
group by CITY,monthname
order by CITY,monthname



select  monthname,CITY, sum(TOTALPRICE) as totalprice from sales
group by CITY,monthname
order by monthname, sum(TOTALPRICE) desc





--ürün kategorilerine göre

SELECT CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS ROWCOUNT_,
SUM(AMOUNT) AS TOTALAMOUNT

FROM SALES
GROUP BY CATEGORY1, CATEGORY2, CATEGORY3,CATEGORY4
ORDER BY CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4


--maðazalarýn müþteri sayýlarý

--bir müþteri 10 adet ürün alabilir dikkat edilmesi gereken nokta fiþnoya bakýlmalý 
SELECT
CITY,FICHENO, COUNT (*) AS ASDET
FROM SALES WHERE MONTHNAME LIKE '%OCAK%' --WHERE monthname ='01. OCAK' -- WHERE MONTHNAME LIKE '%OCAK%'
AND CITY='ADANA'
GROUP BY CITY,FICHENO
SELECT TOP 10 * FROM SALES;

SELECT
CITY, COUNT(FICHENO)
FROM SALES WHERE MONTHNAME LIKE '%OCAK%'
GROUP BY CITY
ORDER BY CITY

-- KERE GERÇEKLEÞEN FÝÞLER
SELECT
CITY, COUNT(DISTINCT FICHENO), COUNT(*)
FROM SALES WHERE MONTHNAME LIKE '%OCAK%'
GROUP BY CITY
ORDER BY CITY


SELECT
CITY, COUNT(DISTINCT CUSTOMERNAME) AS UNIQUECUSTOMER,
COUNT(DISTINCT FICHENO) CUSTOMERCOUNT,
COUNT (*) ITEMCOUNT
FROM SALES WHERE MONTHNAME LIKE '%OCAK%'

GROUP BY CITY
ORDER BY CITY

--BU OLMAZ
SELECT CITY, SUM(TOTALPRICE)
FROM SALES
WHERE TOTALPRICE>40000
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC
--BUDA OLMAZ
SELECT * FROM SALES WHERE TOTALPRICE>40000

--BU DA OLMAZ HAVÝNG LAZIM
SELECT CITY, SUM(TOTALPRICE)
FROM SALES
WHERE SUM(TOTALPRICE)>40000
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC
--BU OLUR
SELECT CITY, SUM(TOTALPRICE)
FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
ORDER BY SUM(TOTALPRICE) DESC

SELECT CITY, SUM(TOTALPRICE) AS TOTALPRICE
, COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
ORDER BY SUM(TOTALPRICE) DESC


SELECT CITY, SUM(TOTALPRICE) AS TOTALPRICE
, COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME)>400
ORDER BY SUM(TOTALPRICE) DESC
