-- ÜRÜNLERÝN FÝYAT ANALÝZÝ join 
SET STATISTICS IO ON
SELECT ITM. ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
MIN(OD.UNITPRICE) AS ENDUSUKFIYAT,
MAX(OD.UNITPRICE) AS ENYUKSEKFIYAT,
AVG(OD.UNITPRICE) AS ORTALAMAFIYAT,
SUM(OD. AMOUNT) AS TOPLAMADET
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID =O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY ITM.ITEMCODE, ITM. ITEMNAME
ORDER BY ITM.ITEMNAME

-- ÜRÜNLERÝN FÝYAT ANALÝZÝ subquery
SET STATISTICS IO ON
select ITM. ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI, 
(select min(UNITPRICE)FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(select MAX(UNITPRICE)FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(select AVG(UNITPRICE)FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMAFIYAT,
(select SUM(AMOUNT)FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAMADET

FROM ITEMS ITM
ORDER BY ITM.ITEMNAME

--YER KAPLAMA OPTÝMÝZASYON OLARAK JOÝN HER YERDE DAHA ÝYÝDÝR



--URUNLERIN FIYAT ANALIZI,EN COK MANGI AY SATILDI
SET STATISTICS IO ON
SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ENDUSUKFIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENYUKSEKFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMAFIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAMADET,
(
SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS AY FROM ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID =O.ID
WHERE OD.ITEMID=ITM.ID
GROUP BY DATEPART(MONTH,O.DATE_)
ORDER BY SUM(AMOUNT) DESC
) AS ENCOKSATILANAY
FROM 
ITEMS ITM
ORDER BY ITM.ITEMNAME


-- ÜRÜNLERÝN FÝYAT ANALÝZÝ join 
SET STATISTICS IO ON
SELECT ITM. ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
MIN(OD.UNITPRICE) AS ENDUSUKFIYAT,
MAX(OD.UNITPRICE) AS ENYUKSEKFIYAT,
AVG(OD.UNITPRICE) AS ORTALAMAFIYAT,
SUM(OD. AMOUNT) AS TOPLAMADET
FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID =O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY ITM.ITEMCODE, ITM. ITEMNAME
ORDER BY ITM.ITEMNAME

-- ÜRÜNLERÝN FÝYAT ANALÝZÝ subquery
SET STATISTICS IO ON
select ITM. ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI, 
(select min(UNITPRICE)FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(select MAX(UNITPRICE)FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(select AVG(UNITPRICE)FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMAFIYAT,
(select SUM(AMOUNT)FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAMADET

FROM ITEMS ITM
ORDER BY ITM.ITEMNAME

--YER KAPLAMA OPTÝMÝZASYON OLARAK JOÝN HER YERDE DAHA ÝYÝDÝR



--JOÝNDE NULL DEÐERLER GELMEZ O YÜZDEN SATIR SAYISI AZDIR SUB DA GELÝR 
SET STATISTICS IO ON
SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,

(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ENDUSUKFIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENYUKSEKFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMAFIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAMADET,

(
SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS AY FROM ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID =O.ID
WHERE OD.ITEMID=ITM.ID
GROUP BY DATEPART(MONTH,O.DATE_)
ORDER BY SUM(AMOUNT) DESC
) AS ENCOKSATILANAY

FROM 
ITEMS ITM

WHERE ITM.ID NOT IN 
(SELECT ITEMID FROM ORDERDETAILS)
ORDER BY 3


-- KULLANICININ SON ADRESÝNÝ BULMA
SELECT U .* ,
(SELECT COUNT (ADDRESSTEXT) FROM ADDRESS WHERE USERID=U.ID) ADRESSAYISI,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID DESC) SONADRES,

(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID) ILKADRES
FROM
USERS U

WHERE U.ID=1

SELECT *FROM USERS