-- Hata veren veritabanı hangisiyse ismini buraya yaz
USE ETRADE4; 
GO

-- Veritabanının sahibini 'sa' (System Administrator) yapıyoruz
EXEC sp_changedbowner 'sa';


SELECT USERS. * FROM
USERS, ADDRESS
WHERE USERS. ID=ADDRESS. USERID

SELECT USERS. *, ADDRESS. ADDRESSTEXT FROM
USERS, ADDRESS
WHERE USERS. ID=ADDRESS. USERID
AND USERS. ID=1


SELECT
U.NAMESURNAME, U.EMAIL, U.GENDER, U.BIRTHDATE, A.ADDRESSTEXT
FROM USERS U, ADDRESS A
WHERE U.ID=A.USERID
AND U.ID=4


SELECT
U. NAMESURNAME AS ADSOYAD,
U.EMAIL MAILADRESI,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
C.COUNTRY AS ULKE,
CT.CITY AS ŞEHİR,
A.ADDRESSTEXT AS ACIKADRES
FROM
USERS U, ADDRESS A, COUNTRIES C, CITIES CT
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID = A.CITYID
AND U.ID=4


SELECT
U. NAMESURNAME AS ADSOYAD,
U.EMAIL MAILADRESI,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
C.COUNTRY AS ULKE, CT.CITY AS SEHIR,
T.TOWN AS ILCE, D.DISTRICT AS SEMT,
A. POSTALCODE AS POSTAKODU,
A. ADDRESSTEXT AS ACIKADRES
FROM
USERS U,ADDRESS A, COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID


-

SELECT
COUNT (U. NAMESURNAME)
FROM
USERS U, ADDRESS A, COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID


-

SELECT
DISTINCT U. NAMESURNAME
FROM
USERS U, ADDRESS A, COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID


SELECT
U.NAMESURNAME, COUNT(A.ID) AS ADRESSAYISI
FROM
USERS U, ADDRESS A, COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
GROUP BY U.NAMESURNAME

SELECT
U.NAMESURNAME, COUNT(A.ID) AS ADRESSAYISI, COUNT(DISTINCT C.COUNTRY) AS ULKESAYISI,
COUNT(DISTINCT CT.ID) SEHIRSAYISI
FROM
USERS U, ADDRESS A, COUNTRIES C,CITIES CT,
TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID

GROUP BY U. NAMESURNAME
HAVING COUNT(A.ID)>2


SELECT CT.CITY, COUNT(U.ID) AS KULLANICISAYISI

FROM USERS U, ADDRESS A, COUNTRIES C, CITIES CT

WHERE U.ID = A.ID AND C.ID = A.COUNTRYID AND CT.ID =A.CITYID

GROUP BY CT.CITY
ORDER BY KULLANICISAYISI DESC


SELECT U.NAMESURNAME, U.EMAIL, C.COUNTRY,ct.CITY , A.ADDRESSTEXT
FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
join CITIES ct on ct.ID = a.CITYID


SELECT ct.CITY, COUNT(u.ID) as kullancısasyısı
FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
join CITIES ct on ct.ID = a.CITYID
group by CT.CITY















































