SELECT * FROM ADDRESS;


insert into USERS (USERNAME_, PASSWORD_, NAMESURNAME, EMAIL, GENDER) 
values ('halim', 'balim','nalim', 'bakim@gmail.com', 'E')

UPDATE CUSTOMERS SET NATION = 'TR ' 

UPDATE CUSTOMERS SET NATION = 'TR ', AGE=DATEDIFF(YEAR,BIRTHDATE, GETDATE()) 


DELETE FROM CUSTOMERS WHERE AGE = 80 
DELETE FROM CUSTOMERS WHERE AGE = 81 

--TRUNCATE ÇOK HIZLIDIR VE TABLONUN İÇİNİ TAMAMEN BOŞALTIR KAYITLARIN HEPSİNİ SİLER
--VERİ EKLEDİĞİNDE SIFIRDAN BAŞLAR
--DELETE İSE SİLİNSEDE TABLO YAIPISI BOZULMAZ DEVAM EDER.
SELECT * FROM CUSTOMERS
--WHERE AGE BETWEEN '21' AND '51'
WHERE CITY IN ('İSTANBUL','ANKARA')

--TEKRAR EDEN SATIRLARI ALMAZ 
SELECT DISTINCT CITY, DISTRICT FROM CUSTOMERS
WHERE CITY='İSTANBUL'

SELECT CITY, DISTRICT FROM CUSTOMERS
WHERE CITY='İSTANBUL'

