CREATE TABLE USERS(
ID INT IDENTITY(1,1),
USERNAME_ VARCHAR(50),
PASSWORD_ VARCHAR(50),
NAMESURNAME VARCHAR(100),
EMAIL VARCHAR(100),
GENDER VARCHAR(1),
BIRTHDATE DATE,
CREATEDDATE DATETIME,
TELNR1 VARCHAR(15),
TELNR2 VARCHAR(15)
 CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED (ID ASC))



CREATE TABLE ITEMS(
ID INT IDENTITY(1,1),
ITEMCODE VARCHAR(50),
ITEMNAME VARCHAR(100),
UNITPRICE FLOAT,
CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50),
CATEGORY3 VARCHAR(50),
CATEGORY4 VARCHAR(50),
BRAND VARCHAR(50)
 CONSTRAINT PK_ITEMS PRIMARY KEY CLUSTERED (ID ASC))
CREATE TABLE PAYMENTS(
ID INT IDENTITY(1,1),
ORDERID INT,
PAYMENTTYPE TINYINT,
DATE_ DATETIME,
ISOK BIT,
APPROVECODE VARCHAR(100),
PAYMENTTOTAL FLOAT
 CONSTRAINT PK_PAYMENTS PRIMARY KEY CLUSTERED (ID ASC))
 CREATE TABLE ADDRESS(
ID INT IDENTITY(1,1), --**ID int PRIMARY KEY IDENTITY(1,1)**, OLABÝLÝRDÝ VE DOÐRUSU DA BUDUR ALTTAKÝ OTOMATÝK OLUÞTURULAN SCRÝPTTEN ALINMIÞTIR.
USERID INT,
COUNTRYID TINYINT,
CITYID SMALLINT,
TOWNID INT,
DISTRICTID INT,
POSTALCODE VARCHAR(10),
ADDRESSTEXT VARCHAR(500)
 CONSTRAINT PK_ADDRESS PRIMARY KEY CLUSTERED (ID ASC))





CREATE TABLE ORDERS(
ID INT IDENTITY(1,1),
USERID INT,
DATE_ DATETIME,
TOTALPRICE FLOAT,
STATUS_ TINYINT,
ADDRESSID INT
 CONSTRAINT PK_ORDERS PRIMARY KEY CLUSTERED (ID ASC))
CREATE TABLE ORDERDETAILS(
ID INT IDENTITY(1,1),
ORDERID INT,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT
 CONSTRAINT PK_ORDERDETAILS PRIMARY KEY CLUSTERED (ID ASC))

 CREATE TABLE COUNTRIES(
ID TINYINT IDENTITY(1,1),
COUNTRY VARCHAR(50)
 CONSTRAINT PK_COUNTRIES PRIMARY KEY CLUSTERED (ID ASC))
CREATE TABLE CITIES(
ID SMALLINT IDENTITY(1,1),
COUNTRYID TINYINT,
CITY VARCHAR(50)
 CONSTRAINT PK_CITIES PRIMARY KEY CLUSTERED (ID ASC))
CREATE TABLE TOWNS(
ID INT IDENTITY(1,1),
CITYID SMALLINT,
TOWN VARCHAR(50)
 CONSTRAINT PK_TOWNS PRIMARY KEY CLUSTERED (ID ASC))
CREATE TABLE DISTRICTS(
ID INT IDENTITY(1,1),
TOWNID INT,
DISTRICT VARCHAR(50)
 CONSTRAINT PK_DISTRICTS PRIMARY KEY CLUSTERED (ID ASC))




CREATE TABLE INVOICES(
ID INT IDENTITY(1,1),
ORDERID INT,
DATE_ DATETIME,
ADDRESSID INT,
CARGOFICHENO VARCHAR(20),
TOTALPRICE FLOAT
 CONSTRAINT PK_INVOICES PRIMARY KEY CLUSTERED (ID ASC))
CREATE TABLE INVOICEDETAILS(
ID INT IDENTITY(1,1),
INVOICEID INT,
ORDERDETAILID INT,
ITEMID INT,
AMOUNT INT,
UNITPRICE FLOAT,
LINETOTAL FLOAT
 CONSTRAINT PK_INVOICEDETAILS PRIMARY KEY CLUSTERED (ID ASC))

 -- --- ADRES BAÐLANTILARI ---
-- Kullanýcý -> Adres
ALTER TABLE ADDRESS ADD CONSTRAINT FK_ADDRESS_USERS FOREIGN KEY (USERID) REFERENCES USERS(ID);
-- Ülke -> Adres
ALTER TABLE ADDRESS ADD CONSTRAINT FK_ADDRESS_COUNTRIES FOREIGN KEY (COUNTRYID) REFERENCES COUNTRIES(ID);
-- Þehir -> Adres
ALTER TABLE ADDRESS ADD CONSTRAINT FK_ADDRESS_CITIES FOREIGN KEY (CITYID) REFERENCES CITIES(ID);
-- Ýlçe -> Adres
ALTER TABLE ADDRESS ADD CONSTRAINT FK_ADDRESS_TOWNS FOREIGN KEY (TOWNID) REFERENCES TOWNS(ID);
-- Semt -> Adres
ALTER TABLE ADDRESS ADD CONSTRAINT FK_ADDRESS_DISTRICTS FOREIGN KEY (DISTRICTID) REFERENCES DISTRICTS(ID);

-- --- HÝYERARÞÝ BAÐLANTILARI (Ýl -> Ýlçe -> Semt) ---
ALTER TABLE CITIES ADD CONSTRAINT FK_CITIES_COUNTRIES FOREIGN KEY (COUNTRYID) REFERENCES COUNTRIES(ID);
ALTER TABLE TOWNS ADD CONSTRAINT FK_TOWNS_CITIES FOREIGN KEY (CITYID) REFERENCES CITIES(ID);
ALTER TABLE DISTRICTS ADD CONSTRAINT FK_DISTRICTS_TOWNS FOREIGN KEY (TOWNID) REFERENCES TOWNS(ID);

-- --- SÝPARÝÞ BAÐLANTILARI ---
-- Sipariþ kime ait?
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USERID) REFERENCES USERS(ID);
-- Sipariþ hangi adrese gidecek?
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_ADDRESS FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS(ID);

-- --- SÝPARÝÞ DETAY BAÐLANTILARI ---
-- Hangi sipariþin detayý?
ALTER TABLE ORDERDETAILS ADD CONSTRAINT FK_ORDERDETAILS_ORDERS FOREIGN KEY (ORDERID) REFERENCES ORDERS(ID);
-- Hangi ürün satýldý?
ALTER TABLE ORDERDETAILS ADD CONSTRAINT FK_ORDERDETAILS_ITEMS FOREIGN KEY (ITEMID) REFERENCES ITEMS(ID);

-- --- FATURA BAÐLANTILARI ---
ALTER TABLE INVOICES ADD CONSTRAINT FK_INVOICES_ORDERS FOREIGN KEY (ORDERID) REFERENCES ORDERS(ID);
ALTER TABLE INVOICEDETAILS ADD CONSTRAINT FK_INVOICEDETAILS_INVOICES FOREIGN KEY (INVOICEID) REFERENCES INVOICES(ID);