-- LEFT, RIGHT, LEN
SELECT LEFT('ÖMER ÇOLAKOÐLU' ,4)
SELECT RIGHT('ÖMER ÇOLAKOÐLU',4)
SELECT LEN('1234567890' )

SELECT LEFT('ÖMER ÇOLAKOÐLU' ,4)
SELECT LEFT('ÖMER ÇOLAKOÐLU', CHARINDEX(' ', 'ÖMER ÇOLAKÐLU' ) )
SELECT RIGHT('ÖMER ÇOLAKOÐLU', len('ÖMER ÇOLAKOÐLU')-CHARINDEX(' ', 'ÖMER ÇOLAKÐLU' ))

SELECT 
LEFT(NAMESURNAME, CHARINDEX(' ', NAMESURNAME ) ), RIGHT(NAMESURNAME, len(NAMESURNAME)-CHARINDEX(' ', NAMESURNAME ))
from USERS


