create procedure SP_GetSales
as
select * from SALES

alter proc SP_GetSales
as
select * from SALES
where CITY = 'BURSA'


alter proc SP_GetSales
@CITY as varchar(50)
as
select * from SALES
where CITY = @CITY

alter proc SP_GetSales
@CITY as varchar(50),
@BEDDATE DATE,
@ENDDATE DATE
as
select * from SALES
where CITY = @CITY AND DATE_ BETWEEN @BEDDATE AND @ENDDATE

--sorgu sýrasýnda parametre göndermediðimizde otomatik deðer göndermek


-- Batch 2: SP_getOrders
ALTER PROC SP_getOrders
@USERNAME AS VARCHAR(100) = '%',
@BEGDATE AS DATETIME = NULL,
@ENDDATE AS DATETIME = NULL,
@CITY AS VARCHAR(100) = '%'
AS
BEGIN
    IF @BEGDATE IS NULL
    BEGIN
        SELECT TOP 1 @BEGDATE = DATE_ FROM ORDERS ORDER BY DATE_ ASC
    END

    IF @ENDDATE IS NULL
    BEGIN
        SELECT TOP 1 @ENDDATE = DATE_ FROM ORDERS ORDER BY DATE_ DESC
    END

    SELECT
        O.ID, O.DATE_, U.USERNAME_, U.NAMESURNAME,
        C.CITY, T.TOWN, D.DISTRICT, A.POSTALCODE, A.ADDRESSTEXT,
        I.ITEMCODE, I.ITEMNAME, I.BRAND, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3, I.CATEGORY4,
        I.UNITPRICE AS ITEMPRICE, OD.UNITPRICE, OD.AMOUNT, OD.LINETOTAL
    FROM ORDERS O
        JOIN USERS U ON U.ID = O.USERID
        JOIN ADDRESS A ON A.ID = O.ADDRESSID
        JOIN CITIES C ON C.ID = A.CITYID
        JOIN TOWNS T ON T.ID = A.TOWNID
        JOIN DISTRICTS D ON D.ID = A.DISTRICTID
        JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
        JOIN ITEMS I ON I.ID = OD.ITEMID
    WHERE 
        U.USERNAME_ LIKE @USERNAME OR @USERNAME IS NULL AND 
        O.DATE_ BETWEEN @BEGDATE AND @ENDDATE AND 
        C.CITY LIKE @CITY
END
GO